name: quehacemos_cba
description: "App de eventos culturales Córdoba - Versión cache optimizada"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI y Estado
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  url_launcher: ^6.3.2
  share_plus: ^11.0.0
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^17.0.0
  app_badge_plus: ^1.2.3
  timezone: ^0.9.0

  # Dates y localización
  intl: ^0.20.2

  # Storage local (para futuro SQLite)
  shared_preferences: ^2.0.0
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true