// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDeeLqW5J4hw4IdxF4wrxSmEdpGRAv5TnU",
    appId: '1:998972257036:web:app-id-placeholder',
    messagingSenderId: '998972257036',
    projectId: 'quehacemos-cba',
    authDomain: 'quehacemos-cba.firebaseapp.com',
    storageBucket: 'quehacemos-cba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDeeLqW5J4hw4IdxF4wrxSmEdpGRAv5TnU",
    appId: '1:998972257036:android:18550c6d86fc8c3eefcf29',
    messagingSenderId: '998972257036',
    projectId: 'quehacemos-cba',
    storageBucket: 'quehacemos-cba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDeeLqW5J4hw4IdxF4wrxSmEdpGRAv5TnU",
    appId: '1:998972257036:ios:app-id-placeholder',
    messagingSenderId: '998972257036',
    projectId: 'quehacemos-cba',
    storageBucket: 'quehacemos-cba.firebasestorage.app',
    iosBundleId: 'com.quehacemos.cba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyDeeLqW5J4hw4IdxF4wrxSmEdpGRAv5TnU",
    appId: '1:998972257036:ios:app-id-placeholder',
    messagingSenderId: '998972257036',
    projectId: 'quehacemos-cba',
    storageBucket: 'quehacemos-cba.firebasestorage.app',
    iosBundleId: 'com.quehacemos.cba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyDeeLqW5J4hw4IdxF4wrxSmEdpGRAv5TnU",
    appId: '1:998972257036:web:app-id-placeholder',
    messagingSenderId: '998972257036',
    projectId: 'quehacemos-cba',
    authDomain: 'quehacemos-cba.firebaseapp.com',
    storageBucket: 'quehacemos-cba.firebasestorage.app',
  );
}